language: c
addons:
  apt:
    packages:
      - bc
      - gcc-arm-linux-gnueabi
      - u-boot-tools
      - debian-archive-keyring
      - debootstrap
script:
  - make kernel
  - cd kernel && git fetch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git v4.4.2 && git rebase FETCH_HEAD
  - apt-get download debian-archive-keyring
  - dpkg-deb fsys-tarfile debian-archive-keyring_*.deb | tar -x --strip-components=4 ./usr/share/keyrings/debian-archive-keyring.gpg
  - make KEYRING_OPT="--keyring debian-archive-keyring.gpg" debs.tar
  - make
deploy:
  provider: releases
  api_key:
    secure: IUxqX9zeAQgR7rzVpLH7sj44JvCqCHNpEJxtwjLrn5573Pw/LBknZCIdmVUeVHqxfiQKVoOxwQ34y7oIBGwXcJWsZS3akxztuxJ0uzN9IK3M2EYvF/oflmaV0MtVKLsdGaDgmciawUXuYObeTdhdkNiEvVngNvp9b/GrClBxLH0wmHqm3LN/zYwQcafGq7s/5SaIzsiMABz0xD4ufy0PRO+RoenrbbncLxmE3vL9UFJJ2IV8eskYanf40EqLujNDeYiMOKUTW76f+Smf6k7FVIMC7GowkPLdEmPYNknNj+AC+KkPmokDaYGBtAc2nOKM9/730QEJe5N7j/tfktlica5wLMyJp77KwEv4WojTvIzY8Lm/JjeG//DueJ7fIKkvLk6kuQcAbClqYb3IGHuHepstO+Q6EvXNrAhR6zJ4Ce0pBK0WMZmpXZ6zpr0folNanrxlto6mfDL2OOpbkG7n7N3j8sEhQRkQpG/IsquJO7pUP5y2AWwxJ9T4kYydbWO4ua+YauOXA9+fMh8nqTjemR821eTd+a6NzgG5NwXXNV2M/3wPSqNz0B8EOK+FN1CGuMDR/GOe7FeuQjoB77k8nADWyO6Gv+9p+n1DQtvjdNG81P49qXF2O6KDkPQhTLtnKR/H4lQqLha8MLLuWfjDVJFePzEIUfoiuAG0fZDQyPQ=
  file:
    - boot.zip
    - rootfs.tar.gz
  on:
    tags: true
