#!/bin/sh -eux
umask 022

debootstrap $DEBOOTSTRAP_OPTS --unpack-tarball "$PWD/debs.tar" "$3" tmp "$2"

rm -f tmp/etc/resolv.conf
rm -f tmp/etc/hostname

rm -f tmp/sbin/init
sed < init.template > tmp/sbin/init -e "s,__MIRROR__,$2,g" -e "s,__SUITE__,$3,g"
chmod 755 tmp/sbin/init

dpkg-deb --fsys-tarfile libeatmydata1.deb | tar -x -C tmp ./usr/lib/arm-linux-gnueabi/libeatmydata.so.1.1.2

cp -r ship/* tmp
chmod 600 tmp/etc/wpa_supplicant/wpa_supplicant.conf

tar -czf "$1" -C tmp .
rm -rf tmp
