#!/bin/sh
### BEGIN INIT INFO
# Provides:          contrast
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO
echo 32 > /sys/devices/soc/d8050800.fb/contrast
